import type { Config } from "tailwindcss";

// Tokens portados del export de diseño de Stitch (Material 3 / esquema celeste).
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#40484e",
        "surface-container-low": "#eef4ff",
        "inverse-surface": "#26313f",
        "on-primary-fixed-variant": "#004c6c",
        "surface-container": "#e4efff",
        "outline-variant": "#bfc7cf",
        "on-background": "#111c29",
        "tertiary-container": "#cbaff5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        outline: "#70787f",
        "on-tertiary-fixed": "#250c49",
        "secondary-container": "#99f2bd",
        background: "#f8f9ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d8e3f5",
        secondary: "#006d43",
        primary: "#00658e",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#001e2e",
        "primary-container": "#7cc4f2",
        "secondary-fixed": "#9cf5c0",
        "error-container": "#ffdad6",
        surface: "#f8f9ff",
        "surface-dim": "#cfdbec",
        "tertiary-fixed-dim": "#d6baff",
        "secondary-fixed-dim": "#80d8a5",
        "on-surface": "#111c29",
        error: "#ba1a1a",
        "inverse-on-surface": "#e9f1ff",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#005231",
        "surface-container-high": "#dee9fb",
        "on-primary": "#ffffff",
        "surface-container-highest": "#d8e3f5",
        tertiary: "#6b5391",
        "on-error-container": "#93000a",
        "surface-tint": "#00658e",
        "on-primary-container": "#005172",
        "on-tertiary-container": "#573f7c",
        "on-secondary-container": "#0a7147",
        "primary-fixed": "#c7e7ff",
        "primary-fixed-dim": "#87cffd",
        "on-secondary-fixed": "#002111",
        "on-tertiary-fixed-variant": "#523b77",
        "tertiary-fixed": "#ecdcff",
        "inverse-primary": "#87cffd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        kpi: "12px",
        button: "12px",
        input: "12px",
      },
      spacing: {
        margin: "24px",
        md: "16px",
        lg: "24px",
        unit: "4px",
        xs: "4px",
        sm: "8px",
        xl: "32px",
        gutter: "20px",
      },
      maxWidth: {
        max_width: "1440px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
      },
      boxShadow: {
        soft: "0px 4px 20px rgba(31, 42, 55, 0.04)",
      },
    },
  },
  plugins: [],
};

export default config;
